service: project-dynamodb

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region : us-west-1
  memorySize: 512
  timeout : 10
  environment: 
    ${file(serverless.env.yml)}

plugins:
    - serverless-dynamodb-local
    - serverless-offline-ssm
    - serverless-offline

custom:
  dynamodb:
    stages:
      - dev
  serverless-offline-ssm:
    stages:
      - dev
    ssm:
      '/hello_test': 'HELLO SSM'
  serverless-offline:
    httpPort: 4000

functions:
  hello:
    handler: src/lambdas/hello.test
    events:
      - http:
          method: GET
          path: hello
          private: true
  createUser:
    handler: src/lambdas/createUser.add
    events:
      - http:
          method: POST
          path: create
          private: true        
  getAllUsers:
    handler: src/lambdas/getAllUsers.get
    events:
      - http:
          method: GET
          path: get-all
          private: true
resources:
  - ${file(src/resources/api-gateway.yml)}
  - ${file(src/resources/dynamo-table.yml)}


    